/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'Robert Clayforth' at '26/07/15 15:54' with Gradle 2.4
 *
 * @author Robert Clayforth, @date 26/07/15 15:54
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
