/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'Robert Clayforth' at '26/07/15 15:54' with Gradle 2.4
 *
 * @author Robert Clayforth, @date 26/07/15 15:54
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
